# Generated by Django 5.1.6 on 2025-11-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название корпуса/дома')),
                ('floors', models.PositiveSmallIntegerField(verbose_name='Этажей')),
                ('apartments_count', models.PositiveIntegerField(verbose_name='Кол-во квартир')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('building', 'Строится'), ('completed', 'Сдан')], default='planned', max_length=20, verbose_name='Статус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='site_1.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Корпус / Дом',
                'verbose_name_plural': 'Корпуса / Дома',
            },
        ),
    ]
