# Generated by Django 5.1.6 on 2025-11-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('concrete', 'Бетон'), ('brick', 'Кирпич'), ('glass', 'Стекло'), ('metal', 'Металл'), ('wood', 'Дерево'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='site_1.material', verbose_name='Материалы'),
        ),
    ]
